### The 'one-dimensional objects'
For this exercise, we are going to define 'one-dimensional objects' with vector
operators, and use special symmetries to make sense of them. The four objects we
are going to explore are:
1. scalar
3. polar vector
4. axial (pseudo) vector
5. pseudoscalar

Scalar: constant: (x, y, z) goes to (x, y, z)  
Polar vector: $\hat{z}$: (x, y, z) goes to (-x, -y, -z)  
Axial (pseudo) vector: $\hat{x} * \hat{y}$: (x, y, z) goes to (x, -y, -z)  
Pseudoscalar: $\hat{z}*(\hat{x} * \hat{y})$: (x, y, z) goes to ()  

- identity
- inversion
- mirror_z: a mirror in the xy-plane
- mirror_y: a mirror in the yz-plane
- rotation_x_180: a 180 degree rotation about the x-axis

In [1]:
import numpy as np # Import numpy

In [2]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, 1])

In [31]:
scalar = np.dot(c, c) # Dot product  
polar_vec = c # No operation  
axial_vec = np.cross(a, b) # Cross product  
pseudo_scalar = np.dot(c, np.cross(a, b)) # Scalar triple product  
#print(scalar)  
#print(polar_vec)  
#print(axial_vec)  
#print(pseudo_scalar)

In [26]:
identity = np.array(
                [[ 1, 0, 0]
                ,[ 0, 1, 0]
                ,[ 0, 0, 1]])

In [27]:
id_scalar = np.dot(identity @ c, identity @ c)
id_polar_vec = identity @ c
id_axial_vec = np.cross(identity @ a, identity @ b)  
id_pseudo_scalar = np.dot(identity @ c, np.cross(identity @ a, identity @ b))
print(id_scalar)  
print(id_polar_vec)  
print(id_axial_vec)  
print(id_pseudo_scalar)

1
[0 0 1]
[0 0 1]
1


In [33]:
inversion = np.array(
                [[-1, 0, 0]
                ,[ 0, -1, 0]
                ,[ 0, 0, -1]])

In [34]:
inversion_scalar = np.dot(inversion @ c, inversion @ c)
inversion_polar_vec = inversion @ c
inversion_axial_vec = np.cross(inversion @ a, inversion @ b)  
inversion_pseudo_scalar = np.dot(inversion @ c, np.cross(inversion @ a, inversion @ b))
print(inversion_scalar)
print(inversion_polar_vec)
print(inversion_axial_vec)
print(inversion_pseudo_scalar)

1
[ 0  0 -1]
[0 0 1]
-1


In [ ]:
mirror_z = np.array(
                [[]
                 ,[]
                 ,[])

In [ ]:
mirror_y = np.array(
                [[]
                 ,[]
                 ,[])

In [ ]:
mirror_x = np.array(
                [[]
                 ,[]
                 ,[])

| 1D object | Identity | Inversion | Mirror_z | Mirror_y | Mirror_x |  Rotation_x_180 |  
|-----------|----------|-----------|----------|----------|----------|----------------|  
| Scalar | 1 | 1| | | | |  
| Polar Vector | 1 |-1 | | | | |  
| Axial Vector | 1 |1 | | | | |  
| Pseudoscalar | 1 | -1| | | | |  